#!/usr/bin/env bash
#
# advisor-upgrade.sh — drive a Spring Application Advisor upgrade for this repo.
#
# What it does, in order:
#   1. Preflight checks (advisor CLI, mvnw, required hand-authored mapping).
#   2. Regenerate the auto-generatable dependency mappings under .advisor/mappings/
#      (the hand-authored spring-boot-jackson3.json is preserved, never touched).
#   3. Export the SPRING_ADVISOR_MAPPING_CUSTOM_* env vars that tell advisor which
#      custom mappings to merge (order + merge strategy taken from advisor.md).
#   4. Run `advisor build-config get`.
#   5. Loop: `advisor upgrade-plan get` -> confirm -> `advisor upgrade-plan apply`
#      -> build check, until the plan converges (no more upgrades) or --max-steps.
#
# The upgrade is applied incrementally by advisor (one Spring generation per step),
# so this script loops until there is nothing left to apply.
#
# Usage:
#   ./advisor-upgrade.sh [options]
#
# Options:
#   -y, --yes           Do not prompt before applying each step (non-interactive / CI).
#       --dry-run       Regenerate mappings + build-config + print the upgrade plan.
#                       Never applies anything. Great for a first, safe run.
#       --skip-mappings Skip mapping regeneration; use the committed files as-is.
#       --verify        Run full `./mvnw verify` after each applied step
#                       (needs the Kafka/Docker infra from docker-compose.yml).
#       --no-build      Skip the build check after each applied step.
#       --max-steps N   Safety cap on the number of upgrade steps (default: 25).
#   -h, --help          Show this help and exit.
#
# Environment:
#   NO_COLOR            Disable coloured output (also auto-disabled when not a TTY).
#
set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Directory this script lives in == repo root. Everything runs from here.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
MAPPINGS_DIR="${SCRIPT_DIR}/.advisor/mappings"

# The hand-authored mapping that carries the Boot 4.0 recipe. It CANNOT be
# regenerated by `advisor mapping create`, so we require + preserve it.
CUSTOM_MAPPING="spring-boot-jackson3.json"

# Auto-generatable mappings: "target-filename|maven-coordinate".
# Extend this list to add more custom mappings.
AUTO_MAPPINGS=(
  "javafaker.json|com.github.javafaker:javafaker"
  "avro.json|org.apache.avro:avro"
  "kafka-streams.json|org.apache.kafka:kafka-streams"
  "kafka.json|org.apache.kafka:kafka_2.13"
)

# Ordered list of mapping files fed to advisor via env vars, with optional
# merge strategy: "filename[:merge-strategy]". Index == position below.
MAPPING_ENV_ORDER=(
  "spring-boot-jackson3.json:override"
  "javafaker.json"
  "avro.json"
  "kafka.json"
  "kafka-streams.json:override"
)

# Defaults (overridable by flags).
ASSUME_YES=0
DRY_RUN=0
SKIP_MAPPINGS=0
BUILD_MODE="install"   # install | verify | none
MAX_STEPS=25

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  BOLD=$'\033[1m'; RED=$'\033[31m'; GREEN=$'\033[32m'
  YELLOW=$'\033[33m'; BLUE=$'\033[34m'; RESET=$'\033[0m'
else
  BOLD=""; RED=""; GREEN=""; YELLOW=""; BLUE=""; RESET=""
fi

banner()  { printf '\n%s========== %s ==========%s\n' "${BOLD}${BLUE}" "$*" "${RESET}"; }
info()    { printf '%s\n' "$*"; }
ok()      { printf '%s✅ %s%s\n' "${GREEN}" "$*" "${RESET}"; }
warn()    { printf '%s⚠️  %s%s\n' "${YELLOW}" "$*" "${RESET}"; }
err()     { printf '%s❌ %s%s\n' "${RED}" "$*" "${RESET}" >&2; }
run()     { printf '%s$ %s%s\n' "${BOLD}" "$*" "${RESET}"; "$@"; }

die()     { err "$*"; exit 1; }

usage() {
  # Print the leading comment block: skip the shebang, print comment lines
  # (stripping the leading "# "), stop at the first non-comment line.
  awk 'NR==1 {next} /^#/ {sub(/^# ?/, ""); print; next} {exit}' "${BASH_SOURCE[0]}"
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

while [[ $# -gt 0 ]]; do
  case "$1" in
    -y|--yes)        ASSUME_YES=1 ;;
    --dry-run)       DRY_RUN=1 ;;
    --skip-mappings) SKIP_MAPPINGS=1 ;;
    --verify)        BUILD_MODE="verify" ;;
    --no-build)      BUILD_MODE="none" ;;
    --max-steps)     shift; [[ "${1:-}" =~ ^[0-9]+$ ]] || die "--max-steps needs a number"; MAX_STEPS="$1" ;;
    --max-steps=*)   MAX_STEPS="${1#*=}"; [[ "$MAX_STEPS" =~ ^[0-9]+$ ]] || die "--max-steps needs a number" ;;
    -h|--help)       usage; exit 0 ;;
    *)               err "Unknown option: $1"; echo; usage; exit 2 ;;
  esac
  shift
done

cd "${SCRIPT_DIR}"

# ---------------------------------------------------------------------------
# 1. Preflight
# ---------------------------------------------------------------------------

banner "Preflight"

command -v advisor >/dev/null 2>&1 || die "advisor CLI not found on PATH. Install Spring Application Advisor first."
ADVISOR_VERSION="$(advisor --version 2>/dev/null | sed -n 's/^Version: //p' | head -1)"
info "Spring Application Advisor: ${ADVISOR_VERSION:-unknown}"
case "${ADVISOR_VERSION}" in
  1.6.*) ok "advisor version looks good" ;;
  *)     warn "This script was written against advisor 1.6.x; behaviour may differ." ;;
esac

[[ -x "${SCRIPT_DIR}/mvnw" ]] || die "Maven wrapper ./mvnw not found or not executable at repo root."
ok "Maven wrapper present"

[[ -f "${MAPPINGS_DIR}/${CUSTOM_MAPPING}" ]] \
  || die "Required hand-authored mapping missing: .advisor/mappings/${CUSTOM_MAPPING} (it cannot be regenerated)."
ok "Custom mapping present and will be preserved: ${CUSTOM_MAPPING}"

command -v git >/dev/null 2>&1 && HAVE_GIT=1 || HAVE_GIT=0

# ---------------------------------------------------------------------------
# 2. Regenerate auto mappings
# ---------------------------------------------------------------------------

# Regenerate a single mapping.
#
# `advisor mapping create -c=<coord>` writes the mapping directly into
# .advisor/mappings/<slug>.json, where <slug> is advisor's own name for the
# project and MAY be empty (producing the file literally named ".json"). It
# does not print the mapping to stdout. So we run the command, locate the json
# file it just wrote (the one newer than a marker; `find -name` matches the
# dotfile ".json" too), and rename it to our chosen target filename.
#
# Returns 0 on success, 1 on (tolerated) failure.
generate_mapping() {
  local target_file="$1" coordinate="$2"
  local target_path="${MAPPINGS_DIR}/${target_file}"
  local marker log_out produced
  marker="$(mktemp)"; log_out="$(mktemp)"

  info "  coordinate: ${coordinate} -> ${target_file} (resolving, may take a minute)…"
  if ! advisor mapping create -c="${coordinate}" >"${log_out}" 2>&1; then
    warn "mapping create failed for ${coordinate} (keeping existing ${target_file} if present)"
    sed 's/^/    /' "${log_out}" | tail -4
    rm -f "${marker}" "${log_out}"
    return 1
  fi

  # The file advisor just wrote is the newest json in the mappings dir.
  produced="$(find "${MAPPINGS_DIR}" -maxdepth 1 -type f -name '*.json' -newer "${marker}" 2>/dev/null | head -1)"
  rm -f "${marker}" "${log_out}"

  if [[ -z "${produced}" ]]; then
    if [[ -f "${target_path}" ]]; then
      warn "  advisor produced no new file; keeping existing ${target_file}"
      return 0
    fi
    warn "  no mapping produced for ${coordinate}"
    return 1
  fi

  if [[ "${produced}" != "${target_path}" ]]; then
    mv -f "${produced}" "${target_path}"
    ok "  wrote ${target_file} (advisor slug: '$(basename "${produced}" .json)')"
  else
    ok "  wrote ${target_file}"
  fi
  return 0
}

if [[ "${SKIP_MAPPINGS}" -eq 1 ]]; then
  banner "Mappings (skipped)"
  info "Using committed .advisor/mappings/*.json as-is (--skip-mappings)."
else
  banner "Regenerating dependency mappings"
  info "Preserving hand-authored mapping: ${CUSTOM_MAPPING}"
  gen_ok=0; gen_fail=0
  for entry in "${AUTO_MAPPINGS[@]}"; do
    file="${entry%%|*}"; coord="${entry#*|}"
    if generate_mapping "${file}" "${coord}"; then
      gen_ok=$((gen_ok + 1))
    else
      gen_fail=$((gen_fail + 1))
    fi
  done
  info ""
  ok "Mappings generated: ${gen_ok} succeeded, ${gen_fail} skipped/failed (failures are tolerated)."
fi

# ---------------------------------------------------------------------------
# 3. Export SPRING_ADVISOR_MAPPING_CUSTOM_* env vars
# ---------------------------------------------------------------------------

banner "Wiring custom mappings into advisor"
idx=0
for entry in "${MAPPING_ENV_ORDER[@]}"; do
  file="${entry%%:*}"
  strategy=""
  [[ "${entry}" == *:* ]] && strategy="${entry##*:}"
  path=".advisor/mappings/${file}"
  if [[ ! -f "${SCRIPT_DIR}/${path}" ]]; then
    warn "mapping file not found, skipping from env: ${path}"
    continue
  fi
  export "SPRING_ADVISOR_MAPPING_CUSTOM_${idx}_FILEPATH=${path}"
  line="SPRING_ADVISOR_MAPPING_CUSTOM_${idx}_FILEPATH=${path}"
  if [[ -n "${strategy}" ]]; then
    export "SPRING_ADVISOR_MAPPING_CUSTOM_${idx}_MERGE_STRATEGY=${strategy}"
    line="${line}  (merge: ${strategy})"
  fi
  info "  ${line}"
  idx=$((idx + 1))
done
ok "Configured ${idx} custom mapping(s)."

# ---------------------------------------------------------------------------
# 4. Build config
# ---------------------------------------------------------------------------

banner "Generating build configuration"
run advisor build-config get
ok "build-config generated."

# ---------------------------------------------------------------------------
# 5. Upgrade loop
# ---------------------------------------------------------------------------

# Heuristic: does the `upgrade-plan get` output contain an actionable upgrade?
#
# advisor lists concrete upgrades under "Projects discovered:" as lines like
#   - micrometer-context-propagation: 1.1.x → 1.2.x
# (the arrow is a Unicode "→"; older/other output may use "->"). The rest of
# the output — the "… could not be included …/blocking upgrades for:" section —
# is always present boilerplate that mentions "upgrade" and version-ish tokens,
# so we must NOT key on those. We key strictly on a "version → version" line:
# its absence means nothing is left to apply (only blocked transitives remain).
plan_is_actionable() {
  local plan_output="$1"
  [[ -n "${plan_output}" ]] || return 1
  grep -qE '[0-9]+\.[0-9]+\.[0-9xX]+[[:space:]]*(→|->|=>)[[:space:]]*[0-9]+\.[0-9]+\.[0-9xX]+' <<<"${plan_output}" \
    && return 0
  return 1
}

# Snapshot of tracked changes, to detect whether an apply actually did anything.
worktree_signature() {
  [[ "${HAVE_GIT}" -eq 1 ]] || { echo "no-git"; return; }
  git -C "${SCRIPT_DIR}" status --porcelain 2>/dev/null | sort | cksum
}

build_check() {
  case "${BUILD_MODE}" in
    none)    info "Build check skipped (--no-build)." ;;
    verify)  run ./mvnw -q verify ;;
    install) run ./mvnw -q -DskipTests install ;;
  esac
}

banner "Upgrade plan"
step=0
applied=0

while :; do
  info ""
  info "${BOLD}--- Reading upgrade plan (applied so far: ${applied}) ---${RESET}"
  plan_output="$(advisor upgrade-plan get 2>&1 || true)"
  printf '%s\n' "${plan_output}"

  if ! plan_is_actionable "${plan_output}"; then
    ok "No further upgrades to apply — the repository is fully upgraded for the configured mappings."
    break
  fi

  if [[ "${DRY_RUN}" -eq 1 ]]; then
    warn "Dry run: stopping before applying (upgrade plan shown above)."
    break
  fi

  step=$((step + 1))
  if [[ "${step}" -gt "${MAX_STEPS}" ]]; then
    warn "Reached --max-steps=${MAX_STEPS}; stopping. Re-run to continue."
    break
  fi

  if [[ "${ASSUME_YES}" -ne 1 ]]; then
    printf '%sApply this upgrade step? [y/N] %s' "${BOLD}${YELLOW}" "${RESET}"
    read -r reply </dev/tty || reply=""
    case "${reply}" in
      y|Y|yes|YES) ;;
      *) warn "Stopping at your request. ${applied} step(s) applied."; break ;;
    esac
  fi

  sig_before="$(worktree_signature)"
  banner "Applying upgrade step ${step}"
  if ! run advisor upgrade-plan apply; then
    die "advisor upgrade-plan apply failed on step ${step}. Review output above; fix and re-run."
  fi
  sig_after="$(worktree_signature)"

  if [[ "${HAVE_GIT}" -eq 1 && "${sig_before}" == "${sig_after}" ]]; then
    warn "This step produced no file changes — treating the plan as converged."
    break
  fi

  applied=$((applied + 1))
  ok "Step ${step} applied."

  banner "Verifying build after step ${step}"
  if ! build_check; then
    err "Build check failed after step ${step}."
    err "Inspect the changes (git diff), fix, then re-run. Applied ${applied} step(s) so far."
    exit 1
  fi
  ok "Build check passed after step ${step}."
done

# ---------------------------------------------------------------------------
# 6. Summary
# ---------------------------------------------------------------------------

banner "Summary"
info "Steps applied this run: ${applied}"

# Best-effort: report the Spring Boot version now declared in a leaf app pom.
leaf_pom="$(grep -rl 'spring-boot-starter-parent' "${SCRIPT_DIR}" --include=pom.xml 2>/dev/null | head -1 || true)"
if [[ -n "${leaf_pom}" ]]; then
  boot_ver="$(grep -A2 'spring-boot-starter-parent' "${leaf_pom}" | sed -n 's:.*<version>\(.*\)</version>.*:\1:p' | head -1 || true)"
  [[ -n "${boot_ver}" ]] && info "Spring Boot version in ${leaf_pom#${SCRIPT_DIR}/}: ${boot_ver}"
fi

if [[ "${applied}" -gt 0 ]]; then
  info ""
  info "Next steps:"
  info "  • Review the changes:  git diff"
  info "  • Run the apps / tests to validate behaviour."
  info "  • Re-run this script to continue if more steps remain."
elif [[ "${DRY_RUN}" -eq 1 ]]; then
  info "Dry run complete — no changes were made."
fi
ok "Done."
